import "bootstrap";
import "../components/planCards.js"
import "../components/typeSelect.js"
import "../components/sizeSelect.js"
import "../components/planSubmit.js"
import "../components/creditCardForm.js"
import '../components/autocomplete';
import "./flatpickr.js";
import '../components/paymentForm.js';
import '../components/toolTip.js';
import '../components/loader.js';
